version: 0.2

phases:
  install:
    commands:
      - npm i -g serverless
      - cd ./server
      - npm i
      - cd ..
      - cd ./client
      - npm i
    finally:
      - cd ..
  pre_build:
    commands:
      - cd ./client
      - npm run lint
      - npm run test
      - cd ..
      - cd ./server
      - npm run lint
    finally:
      - cd ..
  build:
    commands:
#      - cd ./client
#      - sls remove -v
#      - cd ..
      - cd ./server
#      - sls remove -v
      - sls deploy -s poc-02 -v
      - cd ..
      - cd ./client
      - sls deploy -s poc-02 -v


